In [5]:
import pandas as pd
import numpy as np
file_path = r"C:\Users\amit6\OneDrive\Desktop\Intelligent-Retail-Customer-Analytics\Data\raw_data\online_retail_II.xlsx"

excel_file = pd.ExcelFile(file_path)

excel_file.sheet_names

['Year 2009-2010', 'Year 2010-2011']

In [28]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)
pd.set_option("display.float_format", "{:.2f}".format)

In [9]:
df_1 = pd.read_excel(file_path , sheet_name= 'Year 2009-2010')
df_2 = pd.read_excel(file_path , sheet_name= 'Year 2010-2011')
df_1.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [29]:
df_2.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.00,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.00,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.00,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.00,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.00,United Kingdom

In [30]:
print(df_1.info())
print(df_2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      541910 non-null  object
 1   StockCode    541910 non-null  object
 2   Description  540456 non-null  object
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  datetime64[ns]
 5   Price        541910 non-null  float64
 6   Customer ID  406830 non-null  float64
 7   Country      541910 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB
None

In [33]:
print(df_1.shape)
print(df_2.shape)

(525461, 8)
(541910, 8)

In [21]:
print(df_2.isnull().sum())
print("\n")
print(df_1.isnull().sum())

Invoice             0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
Price               0
Customer ID    135080
Country             0
dtype: int64


Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [23]:
print(df_2.duplicated().sum())
print("\n")
print(df_1.duplicated().sum())

5268


6865

In [24]:
print(df_2.describe())
print("\n")
print(df_1.describe())

            Quantity                    InvoiceDate          Price  \
count  541910.000000                         541910  541910.000000
mean        9.552234  2011-07-04 13:35:22.342307584       4.611138
min    -80995.000000            2010-12-01 08:26:00  -11062.060000
25%         1.000000            2011-03-28 11:34:00       1.250000
50%         3.000000            2011-07-19 17:17:00       2.080000
75%        10.000000            2011-10-19 11:27:00       4.130000
max     80995.000000            2011-12-09 12:50:00   38970.000000
std       218.080957                            NaN      96.759765

         Customer ID
count  406830.000000
mean    15287.684160
min     12346.000000
25%     13953.000000
50%     15152.000000
75%     16791.000000
max     18287.000000
std      1713.603074


            Quantity                    InvoiceDate          Price  \
count  525461.000000                         525461  525461.000000
mean       10.337667  2010-06-28 11:37:36.845017856       4.688834
min     -9600.000000            2009-12-01 07:45:00  -53594.360000
25%         1.000000            2010-03-21 12:20:00       1.250000
50%         3.000000            2010-07-06 09:51:00       2.100000
75%        10.000000            2010-10-15 12:45:00       4.210000
max     19152.000000            2010-12-09 20:01:00   25111.090000
std       107.424110                            NaN     146.126914

         Customer ID
count  417534.000000
mean    15360.645478
min     12346.000000
25%     13983.000000
50%     15311.000000
75%     16799.000000
max     18287.000000
std      1680.811316

In [26]:
df_1.describe(include="object")

        Invoice StockCode                         Description         Country
count    525461    525461                              522533          525461
unique    28816      4632                                4681              40
top      537434    85123A  WHITE HANGING HEART T-LIGHT HOLDER  United Kingdom
freq        675      3516                                3549          485852

In [27]:
df_2.describe(include="object")

        Invoice StockCode                         Description         Country
count    541910    541910                              540456          541910
unique    25900      4070                                4223              38
top      573585    85123A  WHITE HANGING HEART T-LIGHT HOLDER  United Kingdom
freq       1114      2313                                2369          495478

## Initial Observations

- The workbook contains two sheets covering 2009–2010 and 2010–2011.
- Both sheets share the same schema.
- Missing values are present in Customer ID and Description.
- Duplicate records exist and will need investigation.
- InvoiceDate is currently stored as a datetime column.
- Quantity and Price distributions will require further analysis during data cleaning.
- Some unusual behavior came out from the description of both the dataframes.